spin_manifest_version = 2

[application]
name = "favicon"
version = "0.2.0"
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = "Favicon server"

[[trigger.http]]
route = "/..."
component = "favicon"

[component.favicon]
source = "favicon.wasm"
# files = ["favicon.ico"]
files = [{ source = "static/", destination = "/" }]
[component.favicon.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o favicon.wasm main.go"
watch = ["**/*.go", "go.mod"]
